---
apiVersion: v1
kind: Secret
metadata:
  name: azuredevops
type: Opaque
data:
  AZP_TOKEN: base64==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: azuredevops
data:
  AZP_URL: https://mycompany.visualstudio.com
  AZP_POOL: "Docker Linux Agent"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azuredevops
  namespace: azuredevops
  labels:
    app: azuredevops
spec:
  selector:
    matchLabels:
      app: azuredevops
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: azuredevops
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: azuredevops
        image: imjoseangel/vstsagent
        imagePullPolicy: IfNotPresent
        env:
          - name: ADV_TOKEN
            valueFrom:
              secretKeyRef:
                name: azuredevops
                key: ADV_TOKEN
          - name: AZP_URL
            valueFrom:
              configMapKeyRef:
                name: azuredevops
                key: ADV_ORG
          - name: AZP_AGENT_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: ADV_POOL
            valueFrom:
              configMapKeyRef:
                name: azuredevops
                key: ADV_POOL
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
